name: "Deploy"
on:
  pull_request:
  push:
permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: pages
env:
  TYPSITE_BIN_NAME: 'typsite-x86_64-unknown-linux-gnu'
  TYPST_RELEASE_NAME: 'typst-x86_64-unknown-linux-musl.zip'
  TYPST_BIN_NAME: 'typst'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    # - uses: typst-community/setup-typst@v4
    - name: Setup Pages
      uses: actions/configure-pages@v4
    - uses: robinraju/release-downloader@v1
      id: typsite-release
      with:
        repository: 'Glomzzz/typsite'
        latest: true
        fileName: ${{ env.TYPSITE_BIN_NAME }}
    - uses: robinraju/release-downloader@v1
      id: typst-release
      with:
        repository: 'Glomzzz/typst'
        latest: true
        fileName: ${{ env.TYPST_RELEASE_NAME }}
    - name: Unzip the release
      run: unzip ${{ env.TYPST_RELEASE_NAME }}

    - name: Extract typst binary
      run: |
        TARBALL=$(find . -name "*.tar.xz" | head -n 1)
        echo "Found tarball: $TARBALL"

        tar -xvf "$TARBALL"

        BIN_PATH=$(find . -type f -name "$TYPST_BIN_NAME" | head -n 1)
        echo "Binary path: $BIN_PATH"
        cp "$BIN_PATH" ./$TYPST_BIN_NAME
    - name: Make binary executable
      run: |
        chmod +x ./$TYPSITE_BIN_NAME
        chmod +x ./$TYPST_BIN_NAME
    # here we have to try multiple times
    # since there are network error caused by typst packages randomly
    - name: Typsite compile
      continue-on-error: true
      id: compile_1
      run: |
          ./$TYPSITE_BIN_NAME c --p packages --t ./$TYPST_BIN_NAME
    - name: Typsite compile (retry 1)
      continue-on-error: true
      id: compile_2
      if: steps.compile_1.outcome == 'failure'
      run: |
          ./$TYPSITE_BIN_NAME c --p packages --t ./$TYPST_BIN_NAME
    - name: Typsite compile (retry 2)
      continue-on-error: true
      id: compile_3
      if: steps.compile_2.outcome == 'failure'
      run: |
          ./$TYPSITE_BIN_NAME c --p packages --t ./$TYPST_BIN_NAME
    - name: Typsite compile (retry 3)
      id: compile_4
      if: steps.compile_3.outcome == 'failure'
      run: |
          ./$TYPSITE_BIN_NAME c --p packages --t ./$TYPST_BIN_NAME
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: ./publish
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
